Detection: # Raising the # for any of the maxSearch can improve detection at the cost of some performance.
  maxSearchCalls: 500 # total calls allowed per Tree detection, the more, the better but not always the answer
  maxSearchWidth: 5 # width radius for search
  maxSearchHeight: 20 # height radius for search
  leavesThreshold: 6 # required leaves required for a valid Tree
  logThreshold: 3 # required logs required for a valid Tree
  logDeviation: 2 # The max distance allowed between logs to be the same "Tree"
  expirationCheckRate: 20 # Check when mini-games are expired per X ticks
  materialConsistency: true # if the leaves should match the log type
  connectHives: true
  searchDirections: # Directions it will look for a connected "Tree" block
    - NORTH
    - NORTH_EAST
    - NORTH_WEST
    - EAST
    - SOUTH
    - SOUTH_EAST
    - SOUTH_WEST
    - WEST
    - UP
    - DOWN
Tree:
  Collapse:
    requiredZones: 3 # requiredZones + (getTreeHeight() / zonesMod)
    zonesMod: 3 # 1 more zone for every X blocks the tree is taller
    requiredPercentage: 75.0 # Hit percentage required before collapse
    branchLifetime: 1 # Seconds before being dropped as an Item
    velocityMod: .3
Zone:
  size: 1
  invisible: true
  entity: SLIME # useless currently
  colliderName: "TREE-COLLIDER"
  timeout: 60 # in seconds
  constraint:
    x: .5
    y: .5
    faceOffset: 0 # offset from the front of block.
  Particles: # updateRate means every X ticks update
    amount: 2
    updateRate: 5
    offsetX: 0
    offsetY: 0.25
    offsetZ: 0
    speed: 0.1
    size: 1
    type: REDSTONE
    options: # Required if particle has optional parameters ex redstone
      R: 255
      G: 127
      B: 127
Sound: # Audio can be any sound in Minecraft's library
  Collapse:
    audio:
      - ITEM_CROSSBOW_QUICK_CHARGE_1
      - ITEM_CROSSBOW_QUICK_CHARGE_2
      - ITEM_CROSSBOW_QUICK_CHARGE_3
      - ITEM_CROSSBOW_LOADING_MIDDLE
      - ITEM_CROSSBOW_LOADING_START
    volume: 10
    pitch: 0.7
    pitchMod: 0.025
    chance: 1 # Chance being 1:X amount (X = chance)
  Land:
    volume: 1
    pitch: 0.7
    chance: 3
  Zone: # Audio can be any sound in Minecraft's library
    audio: BLOCK_BEEHIVE_SHEAR
    pitch: 0.7
    volume: 0.2
    chance: 1
    Hit:
      audio: ITEM_CROSSBOW_LOADING_START
      pitch: 1.0
      volume: 1.0
      chance: 1
    Miss:
      audio: UI_LOOM_TAKE_RESULT
      pitch: 1 .0
      volume: 0.5
      chance: 1
  Drop:
    audio: ENTITY_ITEM_FRAME_ROTATE_ITEM
    pitch: 0.6
    volume: 0.5
    chance: 1