Detection: # Raising the # for any of the maxSearch can improve detection at the cost of some performance.
  maxSearchCalls: 250 # total calls allowed per Tree detection, the more, the better but not always the answer
  maxSearchWidth: 5 # width radius for search
  maxSearchHeight: 20 # height radius for search
  leavesThreshold: 6 # required leaves required for a valid Tree
  logThreshold: 3 # required logs required for a valid Tree
  expirationCheckRate: 20
  materialConsistency: true # if the leaves should match the log type
  connectHives: true
Zone:
  size: 1
  invisible: true
  entity: SLIME
  colliderName: "TREE-COLLIDER"
  timeout: 60 # in seconds
  constraint:
    x: .5
    y: .5
    faceOffset: 0 # offset from the front of block.
  Particles: # updateRate means every X ticks update
    amount: 2
    updateRate: 5
    offsetX: 0
    offsetY: 0.25
    offsetZ: 0
    speed: 0.1
    size: 1
    type: REDSTONE
    options: # Required if particle has optional parameters ex redstone
      R: 255
      G: 127
      B: 127
Sound: # Audio can be any sound in Minecraft's library
  Collapse:
    audio:
      - ITEM_CROSSBOW_QUICK_CHARGE_1
      - ITEM_CROSSBOW_QUICK_CHARGE_2
      - ITEM_CROSSBOW_QUICK_CHARGE_3
      - ITEM_CROSSBOW_LOADING_MIDDLE
      - ITEM_CROSSBOW_LOADING_START
    volume: 10
    pitch: 0.7
    pitchMod: 0.025
    chance: 1 # Chance being 1:X amount (X = chance)
  Land:
    volume: 1
    pitch: 0.7
    chance: 3
  Zone: # Audio can be any sound in Minecraft's library
    audio: UI_LOOM_TAKE_RESULT
    pitch: 0.7
    volume: 0.2